onEvent('recipes', event => {
    event.remove({ id: 'tconstruct:common/flint'})
    event.remove({ id: 'mysticalagriculture:essence/flint' })
    event.remove({ type: 'exnihilosequentia:sieve' })
    event.remove({ id: 'mekanism:processing/lead/ingot/from_nuggets'})
    event.remove({ id: 'thermal:storage/lead_ingot_from_nuggets'})
    event.remove({ id: 'thermal:storage/lead_ingot_from_block'})
    event.remove({ id: 'immersiveengineering:crafting/nugget_lead_to_ingot_lead'})
    event.remove({ id: 'immersiveengineering:crafting/storage_lead_to_ingot_lead'})
    event.remove({ id: 'immersiveengineering:crafting/nugget_copper_to_ingot_copper'})
    event.remove({ id: 'mekanism:processing/copper/ingot/from_nuggets'})
    event.remove({ id: 'thermal:storage/copper_ingot_from_nuggets'})
    event.remove({ id: 'tconstruct:common/materials/copper_ingot_from_nuggets'})
    event.remove({ id: 'tconstruct:common/materials/copper_ingot_from_block'})
    event.remove({ id: 'immersiveengineering:crafting/storage_copper_to_ingot_copper'})
    event.remove({ id: 'create:crafting/materials/copper_ingot_from_decompacting' })
    event.remove({ id: 'mekanism:processing/copper/ingot/from_block'})
    
})